name: garry-arduino
version: '0.1'
summary: A robot snail that will inevitably kill all humans
description: |
  Its not quite ready for that though.
  
grade: devel
confinement: devmode
build-packages: [lsb-release]

parts:
  garry-base:
          plugin: dump
          source: garry-base.tar.bz2
          prime: [-*]

  garry-arduino:
    source: https://github.com/braineniac/garry.git
    source-branch: master
    source-space: ctr_arduino/
    plugin: catkin
    rosdistro: kinetic
    include-roscore: false
    catkin-packages: [ctr_arduino]
    underlay:
            build-path: $SNAPCRAFT_STAGE/opt/ros/kinetic
            run-path: $SNAP/garry-base/opt/ros/kinetic
    after: [garry-base]

  run-system:
    plugin: dump
    stage: [bin/run-system]
    prime: [bin/run-system]
  mountpoint:
    plugin: nil
    install: mkdir $SNAPCRAFT_PART_INSTALL/garry-base
  
apps:
  run:
    command: roslaunch ctr_arduino arduino.launch
